name: Check Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set Node.js 18.x
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version: 18

      - name: Install
        run: yarn --frozen-lockfile

      - name: Check formatting with Prettier
        run: npx prettier --check .
