name: Check Formatting

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '20.9.0'

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        # uses: actions/setup-node@v4
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install
        run: yarn --frozen-lockfile

      - name: Check formatting with Prettier
        run: npx prettier --check .
