name: "Publish"
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - uses: jameshenry/publish-shell-action@47bf83d69c510575ae50d93482aff80aa6c96ebc
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
